# Zillow

In [11]:
import pandas as pd
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px

In [12]:
df = pd.read_csv('/Users/sharon/Documents/GitHub/Coding-Resume/Zillow data/Zip_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_mon.csv')
df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1996-01-31,...,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,NaN,...,957437.0,960802.0,962396.0,963537.0,960187.0,955918.0,949634.0,948112.0,948911.0,954998.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,298619.0,...,794058.0,793957.0,795186.0,796847.0,797731.0,798012.0,798051.0,799653.0,801950.0,806333.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,NaN,...,1420881.0,1423693.0,1424519.0,1420952.0,1414127.0,1407642.0,1407057.0,1404420.0,1402979.0,1402128.0
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,204122.0,...,342423.0,342174.0,342397.0,342883.0,343979.0,344922.0,345504.0,345781.0,346558.0,347253.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,456771.0,...,1000145.0,999819.0,1001592.0,1003223.0,1004383.0,1004370.0,1005620.0,1008258.0,1011170.0,1016459.0

In [9]:
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.read_csv('/Users/sharon/Documents/GitHub/Coding-Resume/Zillow data/Zip_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_mon.csv')

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),

    html.Div(children='''
        Dash: A web application framework for Python.
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])
  
if __name__ == '__main__':
    # For Development only, otherwise use gunicorn or uwsgi to launch, e.g.
    # gunicorn -b 0.0.0.0:8050 index:app.server
    app.run_server(
        port=8050,
        host='0.0.0.0'
    )

Dash is running on http://0.0.0.0:8050/

Dash is running on http://0.0.0.0:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off